// Maps the ISO-ish codes stored on User.preferredLanguage/studyLanguage (see User.ts's enum)
// to the full English name an LLM reliably recognizes — a bare code like "fr" competes poorly
// against an English-heavy prompt, but "French" reads as an unambiguous instruction.
const LANGUAGE_NAMES: Record<string, string> = {
  en: 'English', 'en-GB': 'English (UK)', 'en-AU': 'English (Australia)', 'en-CA': 'English (Canada)',
  es: 'Spanish', 'es-MX': 'Spanish (Mexico)',
  fr: 'French', 'fr-CA': 'French (Canada)',
  de: 'German',
  pt: 'Portuguese', 'pt-PT': 'Portuguese (Portugal)',
  it: 'Italian',
  nl: 'Dutch',
  pl: 'Polish',
  sv: 'Swedish',
  no: 'Norwegian',
  da: 'Danish',
  fi: 'Finnish',
  cs: 'Czech',
  sk: 'Slovak',
  sl: 'Slovenian',
  hr: 'Croatian',
  hu: 'Hungarian',
  ro: 'Romanian',
  el: 'Greek',
  tr: 'Turkish',
  ru: 'Russian',
  uk: 'Ukrainian',
  ar: 'Arabic', 'ar-AE': 'Arabic (UAE)', 'ar-EG': 'Arabic (Egypt)',
  he: 'Hebrew',
  hi: 'Hindi',
  bn: 'Bengali',
  ta: 'Tamil',
  te: 'Telugu',
  kn: 'Kannada',
  ml: 'Malayalam',
  mr: 'Marathi',
  gu: 'Gujarati',
  pa: 'Punjabi',
  ur: 'Urdu',
  'zh-CN': 'Chinese (Simplified)', 'zh-TW': 'Chinese (Traditional)',
  ja: 'Japanese',
  ko: 'Korean',
  vi: 'Vietnamese',
  th: 'Thai',
  ms: 'Malay',
  id: 'Indonesian',
  ca: 'Catalan',
};

export const getLanguageName = (code: string): string => LANGUAGE_NAMES[code] || code;
