// Confirmed 2026-07-28 icon set (75 icons from the real Figma export) — use
// via the <Icon name="..." /> component. The named components below predate
// this and remain in place since 39+ files already depend on them; they are
// not yet migrated to the confirmed icon set/palette.
export { iconRegistry } from './registry';
export type { IconName, IconRegistryEntry } from './registry';

export { EmailIcon } from './EmailIcon';
export { GoogleIcon, AppleIcon, FacebookIcon } from './SocialIcons';
export {
  LogoIcon,
  AuthIcon1,
  AuthIcon2,
  AuthIcon3,
  AuthIcon4,
  AuthIcon5,
  AuthIcon6,
  AuthIcon7,
  AuthIcon8,
  MailIcon,
  BackArrowIcon,
} from './AuthIcons';
export {
  HomeIcon,
  HomeIconFilled,
  LibraryIcon,
  LibraryIconFilled,
  ChatIcon,
  ChatIconFilled,
  ProfileIcon,
  ProfileIconFilled,
  ChevronDownIcon,
  RecordAudioIcon,
  UploadAudioIcon,
  YoutubeIcon,
  PDFDocumentIcon,
  CustomTextIcon,
  ImageIcon,
  EmptyFolderIcon,
  SearchIcon,
  FilterIcon,
  BackupIcon,
  TranscriptIcon,
  CloseIcon,
  ChevronRightIcon,
  CreateNotesIcon,
  ChatPDFIcon,
  AudioWaveLogoIcon,
  ChevronLeftIcon,
  MoreVerticalIcon,
  FolderAddIcon,
  TranslateIcon,
  TranscribeIcon,
  EditPencilIcon,
  FlashcardIcon,
  DocumentFileIcon,
  CheckIcon,
  EditNoteIcon,
  ExportIcon,
  ShareLinkIcon,
  PrintIcon,
  DeleteIcon,
  DeleteLargeIcon,
  QuizIcon,
  RadioSelectedIcon,
  RadioUnselectedIcon,
  ExportSummaryIcon,
  ExportTranscriptIcon,
  ExportAudioIcon,
  FolderColorIcon,
  EmptyFolderLargeIcon,
  PlusIcon,
  FolderCheckIcon,
  CloudUploadIcon,
  AudioFileIcon,
  ProgressCircleCompleteIcon,
  ProgressCircleActiveIcon,
  ProgressCirclePendingIcon,
  ChangeFileIcon,
  PlayCircleIcon,
  TimerIcon,
  MinusIcon,
  QuizCardIcon,
  RadioEmptyIcon,
  RadioFilledIcon,
  RadioCorrectIcon,
  RadioWrongIcon,
  ScoreCircleIcon,
  FABPlusIcon,
  RecordAudioGradientIcon,
  UploadAudioGradientIcon,
  YoutubeGradientIcon,
  PDFDocumentGradientIcon,
  CustomTextGradientIcon,
  ImageGradientIcon,
  AudioFilePreviewIcon,
  VideoFilePreviewIcon,
  NoteFilePreviewIcon,
  TranscriptFilePreviewIcon,
  NotechatLogoIcon,
  ChatWithNoteIcon,
  ChatWithImageIcon,
  ChatWithDocumentIcon,
  SendMessageIcon,
  AttachmentIcon,
  MicrophoneIcon,
  DocumentPreviewSmallIcon,
  ImagePreviewSmallIcon,
  NotePreviewSmallIcon,
  FolderSelectIcon,
  RegenerateIcon,
} from './DashboardIcons';
export { FolderIcon } from './FolderIcon';
export { AudioIcon } from './AudioIcon';
export { VideoIcon } from './VideoIcon';
export { TextIcon } from './TextIcon';
export { DocumentIcon } from './DocumentIcon';